### PR TITLE
Add documentation on how to request Taster shows the Inside Story

### PR DESCRIPTION
**Pull request by jackallnutt**
@cnorthwood, @smaister: Ready for review.

### CODE REVIEW

**Comment by cnorthwood** [comment]
lgtm

**Comment by jackallnutt** [comment]
Holding off on merging until the actual feature in taster is ready to go (and we've marked the harness as a release rather than pre-release)

**Comment by goosewobbler** [comment]
:+1:

**Comment by cnorthwood** [comment]
Actual feature is tested and ready to go now :) Let's get this merged

**Pull request merged**
